// <auto-generated />
namespace Xamine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ManagerProjectReporteeModelUpdated3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManagerProjectReporteeModelUpdated3));
        
        string IMigrationMetadata.Id
        {
            get { return "201904110207299_ManagerProjectReporteeModelUpdated-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
